import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/shared/styles/index.scss";
import { Providers } from "@/providers/providers";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "MovieVault",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <html lang="en">
                <body className={inter.className}>
                    <Header />
                    <div
                        style={{
                            display: "flex",
                            flexDirection: "column",
                            minHeight: "100vh",
                            justifyContent: "space-between",
                        }}
                    >
                        <div style={{ flex: "1 1 auto" }}>{children}</div>
                        <Footer />
                    </div>
                </body>
            </html>
        </Providers>
    );
}
